SAMPLE_SIZE = 100000
HEADER_DATA_ROWS_SAMPLE_SIZE = 20
HEADER_DETECTION_SAMPLE_SIZE = 10
DELIMITER_DETECTION_SAMPLE_SIZE = 10

HEADER_LETTER_PATTERN_BONUS = 0.4
HEADER_TYPE_DIFFERENCE_BONUS = 0.3
HEADER_UNDERSCORE_SPACE_BONUS = 0.2
HEADER_LENGTH_BONUS = 0.2
HEADER_TEXT_VS_STRUCTURED_BONUS = 0.2
HEADER_CASE_CONSISTENCY_BONUS = 0.1
HEADER_CONFIDENCE_CONTRAST_BONUS = 0.1

HEADER_NUMERIC_PENALTY = 0.6
HEADER_DATE_PENALTY = 0.4

HEADER_CONFIDENCE_THRESHOLD = 0.8
HEADER_TYPE_PENALTY_THRESHOLD = 0.5
HEADER_MAX_LENGTH_THRESHOLD = 50
