FK_VALIDITY_BONUS = 0.7

FK_OVERLAP_THRESHOLD = 0.30
FK_VALIDATION_OVERLAP_BONUS = 0.6
FK_VALIDATION_SIZE_BONUS = 0.4
FK_VALIDATION_THRESHOLD = 0.6

FK_NAMING_BONUS = 0.3

FK_EXACT_MATCH_BONUS = 1.0
FK_TABLE_PREFIX_BONUS = 0.8
FK_TABLE_REFERENCE_BONUS = 0.6
FK_WORD_MATCH_BONUS = 0.4

FK_PRIMARY_KEY_TARGET_BONUS = 0.3

