NF2_MIN_ROWS_FOR_ANALYSIS = 10
NF2_MIN_COLUMN_VALUES = 2
NF2_MIN_UNIQUE_KEYS = 3
NF2_MIN_PARTIAL_STRENGTH = 0.9

NF2_PARTIAL_DEPENDENCY_THRESHOLD = 0.95
NF2_FULL_KEY_STRENGTH_THRESHOLD = 0.8
NF2_PARTIAL_STRENGTH_THRESHOLD = 0.8

NF3_MIN_NON_KEY_COLUMNS = 2
NF3_MIN_DETERMINANT_VALUES = 2

NF3_UNIQUENESS_BONUS_MULTIPLIER = 0.2
NF3_MAX_UNIQUENESS_BONUS = 0.1

NF3_CONSISTENCY_PENALTY = 0.5

NF3_BASE_CONFIDENCE_HIGH_THRESHOLD = 0.9
NF3_CONFIDENCE_THRESHOLD = 0.6
NF3_CONSISTENCY_THRESHOLD = 0.5
NF3_BASE_CONFIDENCE_LOW_THRESHOLD = 0.3