PK_COMPOSITE_SIZE = 2

PK_UNIQUENESS_BONUS = 10.0
PK_PRIMARY_NAME_BONUS = 5.0
PK_NOT_NULLABLE_BONUS = 3.0
PK_ID_NAME_BONUS = 3.0
PK_UUID_TYPE_BONUS = 2.0

PK_LONG_TEXT_PENALTY = 2.0

PK_SINGLE_UNIQUENESS_THRESHOLD = 0.95
PK_COMPOSITE_UNIQUENESS_THRESHOLD = 1.0
PK_CONFIDENCE_THRESHOLD = 12.0
PK_TEXT_LENGTH_THRESHOLD = 50
