TYPE_DETECTION_SAMPLE_SIZE = 1000

MAX_VARCHAR_LENGTH = 255
BOOLEAN_SIZE = 1
UUID_CHAR_LENGTH = 36

DECIMAL_SCALE_LIMIT = 4
DECIMAL_PRECISION_MIN = 10
DECIMAL_PRECISION_MAX = 18
DECIMAL_INTEGER_BUFFER = 8

CHAR_BUFFER_MULTIPLIER = 1
VARCHAR_BUFFER_MULTIPLIER = 2

TYPE_DETECTION_CONFIDENCE_THRESHOLD = 0.9
